services:
  httpbin:
    build: ./docker/my_httpbin
    container_name: httpbin
    ports:
      - "5000:5000"
    restart: unless-stopped

  apache:
    build: ./docker/apache
    container_name: apache_http1
    ports:
      - "8081:80"
    depends_on:
      - httpbin
    restart: unless-stopped

  nginx:
    build: ./docker/nginx
    container_name: nginx_http2
    ports:
      - "8082:80"
    depends_on:
      - httpbin
    restart: unless-stopped

  caddy:
    build: ./docker/caddy
    container_name: caddy_http3
    ports:
      - "8083:80"
    depends_on:
      - httpbin
    restart: unless-stopped